# Docker Compose Configuration
# visit https://docs.docker.com/compose/

version: '3.8'
services:
  # app service for your backend
  server:
    container_name: youapp-server
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DATABASE_NAME: youapp
      DATABASE_USER: user
      DATABASE_PASS: user
      DATABASE_URI: mongodb://database:27017
      ACCESS_TOKEN_KEY: 8c8d245f91b6b6ea503629182e39e7812d69cd1acd30fe2c04860a403b675d9209e4a691db54d28b79dfa317f17b913724a1e9a38db280b2fb7652a7788b550b
    ports:
      - '3000:3000'
    depends_on:
      - database

  # start the mongodb service as container
  database:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: user
    volumes:
      - youapp-mongodb:/data/db

volumes:
  youapp-mongodb:
    name: youapp-mongodb